version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  python-bench:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - POSTGRES_HOST=db
      - POSTGRES_DB=scd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  go-bench:
    build:
      context: ./Go
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_DSN=host=db user=postgres password=postgres dbname=scd port=5432 sslmode=disable
volumes:
  pgdata: 