# Generated by Django 4.2.23 on 2025-07-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(db_index=True, max_length=64)),
                ('version', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
                ('rate', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=64)),
                ('contractor_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(db_index=True, max_length=64)),
                ('version', models.IntegerField()),
                ('duration', models.FloatField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_uid', on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='django_example.job')),
            ],
            options={
                'db_table': 'timelogs',
            },
        ),
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(db_index=True, max_length=64)),
                ('version', models.IntegerField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_uid', on_delete=django.db.models.deletion.CASCADE, related_name='payment_line_items', to='django_example.job')),
                ('timelog', models.ForeignKey(db_column='timelog_uid', on_delete=django.db.models.deletion.CASCADE, related_name='payment_line_items', to='django_example.timelog')),
            ],
            options={
                'db_table': 'payment_line_items',
            },
        ),
    ]
