# Generated by Django 4.2.23 on 2025-07-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentlineitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentlineitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='updated_at',
        ),
    ]
